/* eslint-disable */
console.log(CONFIG);
export const {
  GOOGLE_TRACK_ID, FACEBOOK_TRACK_ID, GOOGLE_OPTIMIZE_CONTAINER_ID, FB_APP_ID, PAYPAL_SANBOX_ID, STRIPE_KEY, STRIPE_SECRET_KEY, PAYPAL_PRODUCTION_ID
} = CONFIG;

export const PAYMENT_TYPE = {
  PAYPAL: 'paypal',
  CARD: 'card',
}
